# Generated by Django 5.2.8 on 2025-12-05 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_edit_others_posts', 'Can edit posts created by other users')], 'verbose_name_plural': 'Posts'},
        ),
    ]
